urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.conf import settings

from apps.urls import urlpatterns as apps_urlpatterns
from views import LoadProductsFromExcelView, LoadCardsFromExcelView, LoadSuccessView


admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
	(r'^admin/crop/(?P<app_name>\w+)/(?P<model_name>\w+)/(?P<id>\d+)/$', 'views.crop_image_view'),
	url(r'^load_products/$', LoadProductsFromExcelView.as_view()),
	url(r'^load_cards/$', LoadCardsFromExcelView.as_view()),
	url(r'^load_success/$', LoadSuccessView.as_view()),
     #Redactor
    (r'^upload_img/$', 'views.upload_img'),
    (r'^upload_file/$', 'views.upload_file'),

)

urlpatterns += apps_urlpatterns

apps/faq/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.faq.models import Question

class QuestionForm(forms.ModelForm):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'required':'required',
                'placeholder':'E-mail'
            }
        ),
        required=True
    )
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'required':'required',
                'placeholder':'Имя'
            }
        ),
        required=True
    )
    question = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'required':'required',
                'placeholder':'Вопрос'
            }
        ),
        required=True
    )

    class Meta:
        model = Question
        fields = ('name', 'email', 'question',)

apps/orders/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.orders.models import Order

class RegistrationOrderForm(forms.ModelForm):
    full_name = forms.CharField(error_messages={'required': 'Введите ФИО'}, widget=forms.TextInput(attrs={}))
    phone = forms.CharField(error_messages={'required': 'Введите ваш номер телефона'}, widget=forms.TextInput(attrs={}))

    class Meta:
        model = Order
        exclude = ('create_date','total_price','order_status')

    def clean_phone(self):
        data = self.cleaned_data.get('phone', '')

        if data:
            data = u'+7 ' + data

        return data

templates/pages/default.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras products_extras %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block content %}
<div class="main">
    <br>
    <h3>{{ page.title }}</h3>
    {{ page.content|safe }}
    {% if page.url == '/contacts/' %}
    <script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=fQllmN_3ujySBxoiV6McmECx2a1bvJ4E&width=600&height=450"></script>
    {% endif %}
</div>
<div class="right-aside">
    {% get_card_and_certificate certificate=False %}
    <img class="bulb" src="/media/images/bulb.jpg" alt="">
    <div class="subscribe-form-box">
        <h4>SMS-рассылка</h4>
        <p>Если вы хотите получать информацию о новых поступлениях, то оставьте ваш номер телефона.</p>
        <br>
        <form action="{% url subscribe_url %}" method="POST">
            {% csrf_token %}
            <input type="text" name="return_to" class="hidden" value="{{ request.path }}">
            <div class="input-box">
                <input type="text" name="phone_number">
                <button type="submit" class="button"><span class="text">Отправить</span></button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/pages/index.html
{% extends "base.html" %}

{% load thumbnail %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block center %}
    <div class="text text_page">
        {% if page.image %}
            <p>
                {% thumbnail page.image "374x252" as  small %}
                    <img src="{{ small.url }}" width="{{ small.x }}" height="{{ small.y }}" alt="" />
                {% endthumbnail %}
            </p>
        {% endif %}
        {{ page.content|safe }}
    </div>
{% endblock %}

templates/pages/page_content.html
{% if content %}
    {{ content|safe }}
{% endif %}

templates/pages/registration.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block center %}
    <div class="text text_page">
        <h1>{{ page.title }}</h1>
        {% if page.image %}
            <p>
                {% thumbnail page.image "374x252" as  small %}
                    <img src="{{ small.url }}" width="{{ small.x }}" height="{{ small.y }}" alt="" />
                {% endthumbnail %}
            </p>
        {% endif %}
        {{ page.content|safe }}

    </div>
    <div class="classes2">
        <ul>
            <li><a href="#members">Регистрация пилотов</a></li>
            <li><a href="#guests">Регистрация зрителей</a></li>
        </ul>
    </div>
    <div class="subpage" id="members" style="display: none;">
        <div class="text text_page">
            {{ members.content|safe }}
        </div>
        {% if block_reg %}
            {{ block_reg|safe }}
        {% endif %}
    </div>
    <div class="subpage" id="guests" style="display: none;">
        <div class="text text_page">
            {{ guests.content|safe }}
        </div>
        <form action="#guests" method="post" class="guest_form">
        {% if send %}
            <p>Приглашение отправлено на Ваш адрес электронной почты.</p>
        {% else %}
            <div class="input"><label for="id_name">ФИО</label>{{ form.name }}{{ form.name.errors }}</div>
            <div class="input"><label for="id_phone">Телефон</label>{{ form.phone }}{{ form.phone.errors }}</div>
            <div class="input"><label for="id_email">E-mail</label>{{ form.email }}{{ form.email.errors }}</div>
            <div class="check"><label for="id_parking">{{ form.parking }} Требуется автопарковка</label></div>
            <div class="input">{{ form.captcha }}{{ form.captcha.errors }}</div>
            <div class="submit"><input style="font: 12px/15px 'Arial', sans-serif;" type="submit" value="Получить приглашение" /></div>
        {% endif %}
        </form>
    </div>

{% endblock %}