apps/products/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import url, patterns, include
from views import *


urlpatterns = patterns('',
    url(r'^search/$',search_view, name='search_url'),
    url(r'^search/(?P<category_id>\d+)/$', category_search_view, name='category_search_url'),
    url(r'^products/(?P<pk>\d+)/$',product_view, name='products_detail'),

    # modals urls
    url(r'^catalog/(?P<page_full_path>[\w\d_/-]+)/get_category_modal/$', CategoryModalView.as_view()),
    url(r'^catalog/(?P<page_full_path>[\w\d_/-]+)/get_all_brands_modal/$', BrandsModalView.as_view()),
    url(r'^catalog/(?P<page_full_path>[\w\d_/-]+)/get_all_prop_values_modal/(?P<prop_slug>[\w\d_/-]+)/$', PropValuesModalView.as_view()),
    
    # catalog urls
    url(r'^catalog/all/$', CatalogAllView.as_view(), name='all_catalog_url'),
    url(r'^catalog/(?P<page_full_path>[\w\d_/-]+)/$', CatalogView.as_view(), name='catalog_url'),

    # certificate url
    url(r'^certificate/$', CertificateView.as_view(), name='certificate_url'),

    # card url
    url(r'^card/$', CardView.as_view(), name='card_url'),

    # special offers urls
    url(r'^special_offers/$', SpecialOffersListView.as_view(), name='special_offers_list_url'),
    url(r'^special_offer/(?P<slug>[\w\d_/-]+)/$', SpecialOfferView.as_view(), name='special_offer_url'),

    # sms mailing url
    url(r'^subscribe/$', SMSView.as_view(), name='subscribe_url'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.conf import settings

from apps.urls import urlpatterns as apps_urlpatterns
from views import LoadProductsFromExcelView, LoadCardsFromExcelView, LoadSuccessView


admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
	(r'^admin/crop/(?P<app_name>\w+)/(?P<model_name>\w+)/(?P<id>\d+)/$', 'views.crop_image_view'),
	url(r'^load_products/$', LoadProductsFromExcelView.as_view()),
	url(r'^load_cards/$', LoadCardsFromExcelView.as_view()),
	url(r'^load_success/$', LoadSuccessView.as_view()),
     #Redactor
    (r'^upload_img/$', 'views.upload_img'),
    (r'^upload_file/$', 'views.upload_file'),

)

urlpatterns += apps_urlpatterns

apps/products/models.py
# -*- coding: utf-8 -*-
import os, datetime
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User

from pytils.translit import translify
from django.core.urlresolvers import reverse

from sorl.thumbnail import ImageField
from mptt.models import MPTTModel, TreeForeignKey, TreeManager

from apps.utils.managers import PublishedManager

def str_price(price):
    if not price:
        return u'0'
    value = u'%s' %price
    if price._isinteger():
        value = u'%s' %value[:len(value)-3]
        count = 3
    else:
        count = 6
    if len(value)>count:
        ends = value[len(value)-count:]
        starts = value[:len(value)-count]
        return u'%s %s' %(starts, ends)
    else:
        return value

def file_path_Category(instance, filename):
    return os.path.join('images','category',  translify(filename).replace(' ', '_') )
class Category(MPTTModel):
    parent = TreeForeignKey('self', verbose_name=u'Родительская категория', related_name='children', blank=True, null=True, on_delete=models.SET_NULL)
    name = models.CharField(verbose_name=u'Название', max_length=100)
    alias = models.CharField(verbose_name=u'Алиас', max_length=100)
    full_path = models.CharField(verbose_name=u'Полный путь', max_length=100, unique=True, null=True, blank=True)
    image = ImageField(verbose_name=u'Картинка', upload_to=file_path_Category, null=True, blank=True)
    order = models.IntegerField(verbose_name=u'Порядок сортировки',default=10)
    is_published = models.BooleanField(verbose_name = u'Опубликовано', default=True)

    objects = TreeManager()


    def __unicode__(self):
            return self.name

    class Meta:
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'
        ordering = ['order',]


    class MPTTMeta:
            order_insertion_by = ['order']


    def save(self, *args, **kwargs):
        super(Category, self).save(*args, **kwargs)
        category_set = self.get_ancestors(include_self=True)
        if category_set.count() == 1:
            self.full_path = self.alias
        else:
            path = ''
            for i, category in enumerate(category_set):
                if i>0:
                    path += '/'
                path += category.alias

            self.full_path = path
        super(Category, self).save(*args, **kwargs)
        descendants_set = self.get_descendants(include_self=False)
        if descendants_set.count() > 0:
            for descendant in descendants_set:
                descendant.save()

        Category.objects.rebuild() #rebulding tree


    def is_published_category(self):
        if self.is_published == True:
            is_published = True
        else: 
            is_published = False

        return is_published

    def get_absolute_path(self):
        category_set = self.get_ancestors(include_self=True)
        path = '/'
        for category in category_set:
            path += category.alias
            path += '/'
        return path

    def get_descendants_count(self):
        return self.get_descendants().count()

    def is_empty(self):
        category_set = self.get_descendants(include_self=True)

        products = []
        for cat in category_set:
            for product in cat.product_set.all():
                products.append(product)

        if len(products) > 0:
            is_empty = False
        else: 
            is_empty = True
        return is_empty

    def is_root(self):
        if self.get_root() == self:
            is_root = True
        else:
            is_root = False

        return is_root

    def get_siblings_with_self(self):
        return self.get_siblings(include_self=True)

    def get_products(self):
        return self.product_set.filter(is_published=True)

    def get_variants(self):
        variants = ProductVariant.objects.filter(product__category=self).filter(is_published=True)
        return variants

    def get_products_count(self):
        return self.get_products().count()

    def get_properties(self):
        products = self.product_set.filter(is_published=True).prefetch_related('productvariant_set')
        properties = []

        for product in products:
            product_prop_hash = product.get_property_hash()
            product_prop_hash['prop_values'] = sorted(set(product_prop_hash['prop_values']))

            if properties == []:                
                properties.append(product_prop_hash)
            elif not product.prop_slug in map(lambda x: x['prop_slug'], properties):
                properties.append(product_prop_hash)
            else:
                for prop_value in product_prop_hash['prop_values']:
                    all_prop_values = sum(map(lambda x: x['prop_values'], properties),[])
                    if not prop_value in all_prop_values:
                        for prop_hash in properties:
                            if prop_hash['prop_name'] == product_prop_hash['prop_name']:
                                prop_hash['prop_values'].append(prop_value)

        for prop in properties:
            prop['prop_values'] = sorted(prop['prop_values'])

        return properties

    def get_properties_with_count(self):
        properties = self.get_properties()
        variants = self.get_variants()

        for prop in properties:
            new_prop_values = []
            for value in prop['prop_values']:
                value_hash = {}
                count = variants.filter(prop_value=value).count()
                value_hash['value'] = value
                value_hash['count'] = count
                new_prop_values.append(value_hash)
            
            prop['prop_values'] = new_prop_values
        
        return properties

    def get_brands(self):
        products = self.get_products()
        products_pks = products.values_list('brand', flat=True)
        brands = Brand.objects.filter(pk__in=list(products_pks))

        if brands.count() == 0:
            brands = None

        return brands

    def get_brands_with_count(self):
        brands = self.get_brands()
        brands_with_count = []

        for brand in brands:
            brand_hash = {}
            count = brand.product_set.filter(category=self).count()
            brand_hash['brand'] = brand
            brand_hash['count'] = count
            brands_with_count.append(brand_hash)

        return brands_with_count

    def get_brands_by_latter(self, **kwargs):
        brands = self.get_brands()
        latters = []
        for brand in brands:
            latters.append(brand.name[0])

        brand_list = {}
        for latter in latters:
            brand_list[latter] = []
            for brand in brands:
                if brand.name[0] == latter: 
                    brand_list[latter].append(brand)
        return brand_list

    def has_brands_or_props(self):
        brands = self.get_brands()
        props = [ x for x in self.get_properties() if x['prop_name'] != '' ]

        if props != [] or brands != None:
            has_brands_or_props = True
        else: 
            has_brands_or_props = False

        return has_brands_or_props

    def has_subcategories(self):
        subcategory_set = self.get_descendants(include_self=False)

        if subcategory_set.count() > 0:
            has_subcategories = True
        else:
            has_subcategories = False

        return has_subcategories

    def has_not_empty_subcategories(self):
        subcategory_set = self.get_descendants(include_self=False)

        if len([x for x in subcategory_set if not x.is_empty()]) > 0:
            has_subcategories = True
        else:
            has_subcategories = False

        return has_subcategories

    def get_full_title(self):
        ancestors = self.get_ancestors(include_self=True)

        full_title = ' / '.join([ x.name for x in ancestors ])

        return full_title
        

class Brand(models.Model):
    name = models.CharField(verbose_name=u'Название', max_length=100)
    alias = models.CharField(verbose_name=u'Алиас', max_length=100, unique=True)
    image = ImageField(verbose_name=u'Картинка', upload_to=file_path_Category)
    order = models.IntegerField(verbose_name=u'Порядок сортировки',default=10)
    is_published = models.BooleanField(verbose_name = u'Опубликовано', default=True)

    objects = PublishedManager()

    def __unicode__(self):
            return self.name

    class Meta:
        verbose_name = u'Брэнд'
        verbose_name_plural = u'Брэнды'
        ordering = ['-order', 'name']

    def get_absolute_url(self):
        return u'' #self.alias

    def get_products(self):
        return self.product_set

    def get_products_count(self):
        return self.get_products().count()



def file_path_Product(instance, filename):
    return os.path.join('images','products',  translify(filename).replace(' ', '_') )
class Product(models.Model):
    category = TreeForeignKey(Category, verbose_name=u'Категория', null=True, blank=True)
    brand = models.ForeignKey(Brand, verbose_name=u'Брэнд', null=True, blank=True)
    group = models.CharField(verbose_name=u'Группа в эксэле', max_length=200, null=True, blank=True)
    title = models.CharField(verbose_name=u'Название', max_length=400, null=True, blank=True)
    hint = models.TextField(blank=True, verbose_name=u'Подсказка')
    description = models.TextField(blank=True)
    full_description = models.TextField(blank=True)
    image = ImageField(verbose_name=u'Картинка', upload_to=file_path_Product,blank=True)
    prop_name = models.CharField(verbose_name=u'Название свойства', max_length=200, null=True, blank=True)
    prop_slug = models.CharField(verbose_name=u'Техническое название свойства на латинице', max_length=200, null=True, blank=True)
    prop_label = models.CharField(verbose_name=u'Обозначение свойства', max_length=200, null=True, blank=True)

templates/products/_catalog_1_level.html
{% load siteblocks_extras products_extras thumbnail orders_extras %}

<div class="main">
	{% if current_category == None %}
	<br><br><br>
	{% else %}
    <div class="breadcrumbs">
        <ul class="menu">
            {% for cat in current_category.get_ancestors %}
            <li><a href="{% url catalog_url cat.full_path%}">{{ cat.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <h3 class="top-heading">{{ current_category.name }}</h3>
    {% endif %}
    {% for product in object_list %}
        {% include 'products/_product.html' with product=product %}
    {% empty %}
    Товаров не найдено.
    {% endfor %}

    {% if is_paginated and page_obj.paginator.num_pages > 1 %}
        {% include 'shared/_pagination.html' %}
    {% endif %}
</div>
<div class="right-aside">
    {% block_cart %}
    {% if not current_category == None %}
        {% if current_category.is_root %}
            <div class="menu">
                <ul class="vertical">
                    {% for category in current_category.get_siblings_with_self %}
                    <li {% if category == current_category %}class="current"{% endif %}>
                        <div class="wrap"><a href="{% url catalog_url category.full_path %}">{{ category.name }}</a></div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        {% else %}
            <div class="menu">
                <ul class="vertical">
                    {% for category in current_category.get_siblings_with_self %}
                    {% if not category.is_empty %}
                    <li {% if category == current_category %}class="current"{% endif %}>
                        <div class="wrap"><a href="{% url catalog_url category.full_path %}">{{ category.name }}</a></div>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endif %}
    <br>
    
    <form action="" id="filters-form" method="GET">
        {% if current_category.get_brands %}
        <div class="filter">
            <h4>Брэнды</h4>
            <div class="drop-down">
                <div class="title"a><a href="/catalog{{current_category.get_absolute_path}}get_all_brands_modal/" class="fancybox fancybox.ajax">все</a></div>
            </div>
            <ul class="filter-menu">
                {% for brand in current_category.get_brands_with_count %}
                <li class="checkbox-box">
                    <span class="checkbox {% if brand.brand.id|slugify in params_brands %}checked{% endif %}">
                        <input type="checkbox" name="brands" value="{{brand.brand.id}}" {% if brand.brand.id|slugify in params_brands %}checked="checked"{% endif %}>
                    </span>
                    {{ brand.brand.name}}  <span class="hint">{{ brand.count }}</span>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {% for property in current_category.get_properties_with_count %}
            {% if not property.prop_name == '' %}
            <div class="filter">
                <h4>{{ property.prop_name|upper }}</h4>
                <div class="drop-down">
                    <div class="title"><a href="/catalog{{current_category.get_absolute_path}}get_all_prop_values_modal/{{property.prop_slug}}/" data-prop-slug="prop_{{property.prop_slug}}" class="fancybox fancybox.ajax">все</a></div>
                </div>
                <ul class="filter-menu">
                    {% for prop_value in property.prop_values|slice:":5" %}
                    {% if prop_value and prop_value.value %}
                    <li class="checkbox-box">
                        <span class="checkbox {% if prop_value.value in params_props|keyvalue:property.prop_slug %}checked{% endif %}">
                            <input type="checkbox" name="prop_{{ property.prop_slug }}" value="{{prop_value.value}}" 
                             {% if prop_value.value|slugify in params_props|keyvalue:property.prop_slug %}checked="checked"{% endif %}>
                        </span>
                        {{ prop_value.value }} {{ property.prop_label }}  <span class="hint">{{ prop_value.count }}</span>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        {% endfor %}
        <button type="submit" class="button"><span class="text">Применить</span></button>
    </form>
</div>

templates/products/_catalog_2_level.html
{% load pymorphy_tags thumbnail products_extras orders_extras %}

<div class="main">
    {% if current_category == None %}
    <br><br>
    {% else %}
    <div class="breadcrumbs">
        <ul class="menu">
            {% for cat in current_category.get_ancestors %}
            <li><a href="{% url catalog_url cat.full_path%}">{{ cat.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <h3 class="top-heading">{{ current_category.name }}</h3>
    {% endif %}
    {% for category in current_category.get_children %}
        {% if not category.is_empty %}
        <div class="product">
            {% if category.image %}
            <a href="{% url catalog_url category.full_path %}" class="img-link">
            {% thumbnail category.image "x120" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
            {% endthumbnail %}
            </a>
            {% else %}
            <a href="{% url catalog_url category.full_path %}" class="img-link">
                <img src="/media/images/noimage.png" alt="">
            </a>
            {% endif %}        
            <div class="description">
                <div class="title"><a href="{% url catalog_url category.full_path %}">{{ category.name }}</a></div>
                <div class="volume">{{ category.product_set.count }} {{ 'товар'|plural:category.product_set.count }}</div>
            </div>
        </div>
        {% endif %}
    {% empty %}
    Товаров не найдено.
    {% endfor %}
</div>
<div class="right-aside">
    {% block_cart %}
    {% get_card_and_certificate %}
    <img class="bulb" src="/media/images/bulb.jpg" alt="">
    <div class="subscribe-form-box">
        <h4>SMS-рассылка</h4>
        <p>Если вы хотите получать информацию о новых поступлениях, то оставьте ваш номер телефона.</p>
        <br>
        <form action="{% url subscribe_url %}" method="POST">
            {% csrf_token %}
            <input type="text" name="return_to" class="hidden" value="{{ request.path }}">
            <div class="input-box">
                <input type="text" name="phone_number">
                <button type="submit" class="button"><span class="text">Отправить</span></button>
            </div>
        </form>
    </div>
</div>
{% if is_paginated and page_obj.paginator.num_pages > 1 %}
    {% include 'shared/_pagination.html' %}
{% endif %}

templates/products/_catalog_3_level.html
{% load pymorphy_tags thumbnail products_extras orders_extras %}

<div class="main">
    <h3 class="top-heading">{{ current_category.name }}</h3>
    {% for category in current_category.get_children %}
    {% if not category.is_empty %}
    <h4 class="category-2-level-heading">{{ category.name }}</h4>
        {% for inner_category in category.get_children %}
        {% if not inner_category.is_empty %}
        <div class="product">
            {% if inner_category.image %}
            <a href="{% url catalog_url inner_category.full_path %}" class="img-link">
            {% thumbnail inner_category.image "x120" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
            {% endthumbnail %}
            </a>
            {% else %}
            <a href="{% url catalog_url inner_category.full_path %}" class="img-link">
                <img src="/media/images/noimage.png" alt="">
            </a>
            {% endif %}        
            <div class="description">
                <div class="title"><a href="{% url catalog_url inner_category.full_path %}">{{ inner_category.name }}</a></div>
                <div class="volume">{{ inner_category.product_set.count }} {{ 'товар'|plural:inner_category.product_set.count }}</div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    <div class="catalog-clear"></div>
    {% endif %}
    {% empty %}
    Товаров не найдено.
    {% endfor %}
</div>
<div class="right-aside">
    {% block_cart %}
    {% get_card_and_certificate %}
    <img class="bulb" src="/media/images/bulb.jpg" alt="">
    <div class="subscribe-form-box">
        <h4>SMS-рассылка</h4>
        <p>Если вы хотите получать информацию о новых поступлениях, то оставьте ваш номер телефона.</p>
        <br>
        <form action="{% url subscribe_url %}" method="POST">
            {% csrf_token %}
            <input type="text" name="return_to" class="hidden" value="{{ request.path }}">
            <div class="input-box">
                <input type="text" name="phone_number">
                <button type="submit" class="button"><span class="text">Отправить</span></button>
            </div>
        </form>
    </div>
</div>
{% if is_paginated and page_obj.paginator.num_pages > 1 %}
    {% include 'shared/_pagination.html' %}
{% endif %}

templates/products/_get_footer_product.html
{% load thumbnail %}

{% if product %}
<div class="bottle">
	<a href="{% url products_detail product.id %}">
	{% thumbnail product.image "x144" as im %}
    	<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
    {% empty %}
        <img src="/media/images/footer-product-noimage.png">
    {% endthumbnail %}
    </a>
    <div class="bubble">
        <div class="bubble-text">
            <a href="{% url products_detail product.id %}">{{product.title}}</a><br>
            {{product.description}}
        </div>
    </div>
</div>
{% endif %}

templates/products/_product.html
{% load thumbnail %}

<div class="product">
    <a href="/products/{{ product.id }}" class="img-link">
        {% if product.image %}
        {% thumbnail product.image "180x120" format="PNG" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
        {% empty %}
            <img src="/media/images/noimage.png" alt="">
        {% endthumbnail %}
        {% else %}
            <img src="/media/images/noimage.png" alt="">
        {% endif %}
    </a>   
    <div class="description">
        <div class="title"><a href="/products/{{ product.id }}">{{ product.title }}</a></div>
        {% if product.get_property %}
        <div class="volume">{{ product.get_property|safe }}</div>
        {% endif %}
        <div class="price">{{ product.get_price|safe }}</div>
    </div>
</div>

templates/products/brands_modal.html
<div class="modals">
<div class="brands" id="brands-modal">
			<div class="modal-header"></div>
			<div class="modal-page">
				<form action="" method="GET">
				<div class="modal-column">
					{% for key, value in brands.items %}
					<div class="filter">
						<h4>{{key|upper}}</h4>
						<ul class="filter-menu">
							{% for brand in value %}
							<li class="checkbox-box">
			                    <span class="checkbox {% if brand.id|slugify in params_brands %}checked{% endif %}">
			                        <input type="checkbox" name="brands" value="{{brand.id}}" {% if brand.id|slugify in params_brands %}checked="checked"{% endif %}>
			                    </span>
			                    <span class="text">{{brand.name}}</span>
			                </li>
							{% endfor %}
						</ul>
					</div>
					{% endfor %}
					<div class="hidden">
					{% for key, value in params_props.items %}
						{% for prop_value in value %}
							<input type="checkbox" checked="checked" name="prop_{{key}}" value="{{prop_value}}">
						{% endfor %}
					{% endfor %}
					</div>
				</div>
				<div class="filters-bottom">
					<button type="submit" class="button"><span class="text">Применить фильтр</span></button>
					<div class="cancel">или <a href="">отменить и закрыть окно</a></div>
				</div>
				</form>
			</div>
			<div class="modal-footer"></div>
		</div>
</div>

templates/products/catalog.html
{% extends 'base.html' %}

{% block content %}
	{% if category_level == None or category_level == 3 %}
		{% include 'products/_catalog_3_level.html' %}
	{% elif category_level == 1 %}
		{% include 'products/_catalog_1_level.html' %}
	{% elif category_level == 2 %}
		{% include 'products/_catalog_2_level.html' %}
	{% endif %}
{% endblock %}

templates/products/category_modal.html
<div class="modals">
<div class="brands" id="brands-modal">
			<div class="modal-header"></div>
			<div class="modal-page">
				{% for category in category.get_children %}
				{% if category.is_published_category %}
				<div class="modal-column">						
					<h4><a href="{% url catalog_url category.full_path %}">{{category.name}}</a></h4>
					{% if category.is_published_category %}
						{% if category.get_children.count > 0 %}
						<ul class="filter-menu category-menu">
						{% for inner_category in category.get_children %}
							<li><a href="{% url catalog_url inner_category.full_path %}">{{inner_category.name}}</a></li>
						{% endfor %}
						</ul>	
						{% endif %}		
					{% endif %}			
				</div>
				{% endif %}
				{% endfor %}
			</div>
			<div class="modal-footer"></div>
		</div>
</div>

templates/products/certificate.html
{% extends 'base.html' %}

{% load thumbnail siteblocks_extras products_extras orders_extras%}

{% block content %}
<div class="main">
	<br>
	<h3 class="top-heading">Подарочный сертификат</h3>
	<div class="cert-text">
		<div class="img-box">
			<img src="/media/images/certificate.jpg" alt="">
		</div>
		<p>Подарочные сертификаты  «Шарм» — идеальный подарок на любой вкус.</p>
		<p>С ними Ваши близкие, друзья или коллеги смогут выбрать себе подарок из более 30 000 наименований парфюмерии и косметики, представленных в нашем магазине.</p>
	</div>
	<br>
	<div>Сертификаты имеют разные номиналы:</div>

	<div>
	{% for certificate in certificate_set %}
	<div class="cert-box">
		{% thumbnail certificate.image "120" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
        {% empty %}
        	<img src="/media/images/certificate-no-image.png" alt="">
        {% endthumbnail %}
		<div class="volume">{{certificate.value}} рублей.</div>
	</div>
	{% empty %}
	<div>Сертификатов не найдено.</div>
	{% endfor %}
	</div>

	<p>{{cert_text}}</p>
</div>
<div class="right-aside">
    {% block_cart %}
    {% get_card_and_certificate certificate=False %}
    <img class="bulb" src="/media/images/bulb.jpg" alt="">
    <div class="subscribe-form-box">
    	<h4>SMS-рассылка</h4>
    	<p>Если вы хотите получать информацию о новых поступлениях, то оставьте ваш номер телефона.</p>
    	<br>
    	<form action="{% url subscribe_url %}" method="POST">
    		{% csrf_token %}
    		<input type="text" name="return_to" class="hidden" value="{{ request.path }}">
	    	<div class="input-box">
				<input type="text" name="phone_number">
				<button type="submit" class="button"><span class="text">Отправить</span></button>
			</div>
	    </form>
    </div>
</div>
{% endblock %}

templates/products/product_category_search_list.html
{% extends 'base.html' %}

{% load thumbnail siteblocks_extras products_extras orders_extras pymorphy_tags %}

{% block content %}
        <div class="main">
            <br>
            <h3 class="top-heading">Результаты поиска</h3>
            <h4>в категории "{{category.get_full_title}}"</h4>
            <p>По запросу "{{ search_q }}" найдено: {{ product_count }} {{ 'товар'|plural:product_count }}</p>
                <div class="search-category-box">

                {% for product in product_list %}
                    {% include 'products/_product.html' with product=product %}
                {% endfor %}

                </div>
        </div>
{% endblock %}

templates/products/product_search_list.html
{% extends 'base.html' %}

{% load thumbnail siteblocks_extras products_extras orders_extras pymorphy_tags %}

{% block content %}
        <div class="main">
            <br>
            <h3 class="top-heading">Результаты поиска</h3>
            <p>По запросу "{{ search_q }}" найдено: {{ product_count }} {{ 'товар'|plural:product_count }}</p>
            {% regroup product_list by category as products %}

            {% for category in products %}
                <div class="search-category-box">
                {% with category.list|length as products_count %}
                <h4>{{ category.grouper.get_full_title }}  <span class="hint">{{ products_count }} {{ 'товар'|plural:products_count }}</span></h4>
                

                {% for product in category.list|slice:'3' %}
                    {% include 'products/_product.html' with product=product %}
                {% endfor %}

                {% if products_count > 3 %}
                <div class="all-search-link">
                <a href="{% url category_search_url category.grouper.id %}?q={{ search_q }}">Все найденные товары в категории «{{ category.grouper.get_full_title }}»</a>
                </div>
                {% endif %}
                {% endwith %}
                </div>
            {% endfor %}
        </div>
{% endblock %}

templates/products/prop_values_modal.html
{% load siteblocks_extras %}

<div class="modals">
<div class="brands" id="brands-modal">
			<div class="modal-header"></div>
			<div class="modal-page">
				<div class="modal-column">
					<div class="filter">
						<h4 class="modal-column-header">{{current_props.prop_name|upper}}</h4>
						<ul class="filter-menu">
							{% for prop_value in current_props.prop_values %}
			                {% if prop_value %}
		                    <li class="checkbox-box">
		                        <span class="checkbox {% if prop_value.value|slugify in params_props|keyvalue:current_props.prop_slug %}checked{% endif %}">
		                            <input type="checkbox" name="prop_{{ current_props.prop_slug }}" value="{{prop_value.value}}" 
		                             {% if prop_value.value|slugify in params_props|keyvalue:current_props.prop_slug %}checked="checked"{% endif %}>
		                        </span>
		                        <span class="text">{{ prop_value.value }} {{ current_props.prop_label }}</span>
		                    </li>
		                    {% endif %}
							{% endfor %}
						</ul>
					</div>
				</div>
				<div class="filters-bottom">
					<button type="submit" class="button"><span class="text">Применить фильтр</span></button>
					<div class="cancel">или <a href="">отменить и закрыть окно</a></div>
				</div>
			</div>
			<div class="modal-footer"></div>
		</div>
</div>